# https://taskfile.dev

version: '3'

tasks:

  default:
    cmds:
      - go run main.go create_agent.json

  create-agent:
    desc: Creates agent from create_agent.json file.
    cmds:
      - go run main.go json/create_agent.json
