name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "dgillis-dev" ]
  pull_request:
    branches: [ "main", "dgillis-dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 'Create .env file'
        run: |
          touch .env
          echo CLI_CONNECTION_NAME=ga_dev_keypair_auth >> .env
          echo DEMO_DATABASE_NAME=ins_co >> .env
          echo DEMO_SCHEMA_NAME=ins_co.loss_claims >> .env
          echo INTERNAL_NAMED_STAGE=@ins_co.loss_claims.loss_evidence >> .env
          echo FILE_UPLOAD_DIR="../../upload" >> .env
          echo STREAMLIT_APP_DIR=streamlit >> .env
          cat .env

      # Set up Taskfile CLI
      - name: Setup Taskfile CLI
        uses: go-task/setup-task@v1.0.0

        # Snowflake CLI installation
      - name: Set up Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v2.0
        with:
          default-config-file-path: ".snowflake/config.toml"

        # Use the CLI
      - name: Execute Snowflake CLI command
        env:
          SNOWFLAKE_CONNECTIONS_GA_DEV_KEYPAIR_AUTH_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_CONNECTIONS_GA_DEV_KEYPAIR_AUTH_PRIVATE_KEY_RAW: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_RAW }}
        run: task test-snow-connection
